### ISSUE TITLE
Panic on OIDC login

### ISSUE THREAD

**Issue by titpetric** [crusttech/crust#104]
Using `api-system:latest` against DIDMOS_VERSION v2.0.1

~~~
2019/03/21 13:43:29 server.go:2926: http: panic serving 172.25.0.2:47346: runtime error: invalid memory address or nil pointer dereference
goroutine 424 [running]:
net/http.(*conn).serve.func1(0xc420604dc0)
        /usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x984ac0, 0xd82b40)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/crusttech/crust/vendor/github.com/crusttech/go-oidc.(*UserInfo).Claims(0x0, 0x92ca40, 0xc420276300, 0xaacfe0, 0xc420354c00)
        /go/src/github.com/crusttech/crust/vendor/github.com/crusttech/go-oidc/oidc.go:181 +0x26
github.com/crusttech/crust/system/rest.(*openIdConnect).HandleOAuth2Callback(0xc4202520c0, 0x7f9a0ed09c98, 0xc4204c6fc0, 0xc4206def00)
        /go/src/github.com/crusttech/crust/system/rest/oidc.go:169 +0x3c9
github.com/crusttech/crust/system/rest.(*openIdConnect).HandleOAuth2Callback-fm(0x7f9a0ed09c98, 0xc4204c6fc0, 0xc4206def00)
        /go/src/github.com/crusttech/crust/system/rest/router.go:36 +0x48
~~~

**Comment by titpetric** [comment]
This is in triage, pushed to `latest`. Error handling was missing, we return error now so as least we'll know the underlying cause.
